[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0070C0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#262626"
